[package]
name = "seichi915Backup"
version = "1.0.0"
authors = ["Sasaki Touma <sasakitouma@yahoo.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
chrono = "0.4.19"
zip = "0.5.9"